package com.slabbed.gametest;

import java.util.List;

/**
 * The registered test classes and the test-content initialisers, in registration order. This list
 * replaces the Fabric test mod's entrypoint declarations; tools/expected-gametest-count.py reads
 * CLASSES to compute the suite count the run must report.
 */
public final class SlabbedGameTestClasses {
    private SlabbedGameTestClasses() {
    }

    public static final List<String> CLASSES = List.of(
            "com.slabbed.test.ScaffoldingLoweredStandTest",
            "com.slabbed.test.ChainUnderLoweredFullBlockCapTest",
            "com.slabbed.test.GhostLoweredCollisionProofTest",
            "com.slabbed.test.ItemFrameWysiwygBoxTest",
            "com.slabbed.test.HangingSeatRememberedTest",
            "com.slabbed.test.HangingLoadDeferralTest",
            "com.slabbed.test.TrampledSupportConversionTest",
            "com.slabbed.test.Slabbed2612LoweringContractTest",
            "com.slabbed.test.Slabbed2612DyFingerprintTest",
            "com.slabbed.test.Slabbed2612UseOnPlacementTest",
            "com.slabbed.test.Slabbed2612RestingDyTest",
            "com.slabbed.test.Slabbed2612ConnectorSurvivalTest",
            "com.slabbed.test.Slabbed2612CollisionDepthTest",
            "com.slabbed.test.Slabbed2612CompoundMatrixTest",
            "com.slabbed.test.RedstoneGateOnTerrainSlabsPlacementTest",
            "com.slabbed.test.SlabHeightStepCullGh24Test",
            "com.slabbed.test.SlabOnSlabVerticalAnchorTest",
            "com.slabbed.test.DecorativeObjectSupportAnchorTest",
            "com.slabbed.test.SlabVerticalSupportTerrainSlabsGuardTest",
            "com.slabbed.test.FloorTorchSupportDyTest",
            "com.slabbed.test.BottomSlabSpawnProofTest",
            "com.slabbed.test.CompatEligibilityPredicateTest",
            "com.slabbed.test.CeilingHungDecorationFreezeAnchorTest",
            "com.slabbed.test.FenceWallVisibleSupportDyTest",
            "com.slabbed.test.CantileverBfsTerrainSlabsGuardTest",
            "com.slabbed.test.TerrainSlabsOwnSlabDyGuardTest",
            "com.slabbed.test.SlabLaneConduitTerrainSlabsGuardTest",
            "com.slabbed.test.SlabdyRowFormatterFieldsTest",
            "com.slabbed.test.ShippedDebugCommandsTest",
            "com.slabbed.test.client.BetaNoticeSessionGateTest",
            "com.slabbed.test.client.BetaNoticeDismissedWorldsTest",
            "com.slabbed.test.client.BetaNoticeDismissFeedbackTest",
            "com.slabbed.test.client.BetaNoticeVersionChannelTest",
            "com.slabbed.test.RenderRegionBoundaryReadTest",
            "com.slabbed.test.EnvironmentFillEligibilityTest",
            "com.slabbed.test.CompatOffsetDeferralPinTest",
            "com.slabbed.test.LoweredSeatFreezeTest",
            "com.slabbed.test.FloorMountedIsNotHangingTest",
            "com.slabbed.test.ReplaceableCellSeatTest",
            "com.slabbed.test.ThinLayerOwnCellPlacementTest",
            "com.slabbed.test.WallSignAboveSlabTest",
            "com.slabbed.test.RelocatedPlacementAimTest",
            "com.slabbed.test.BottomSlabLoweredByCarrierBelowTest",
            "com.slabbed.test.BlockEntityNeverPopTest",
            "com.slabbed.test.BlockEntityCantileverTest",
            "com.slabbed.test.BlockEntityCantileverTerrainSlabsGuardTest",
            "com.slabbed.test.GeometricRemeshSchedulerTest",
            "com.slabbed.test.LiveCursorIntentRecorderCaptureGameTest",
            "com.slabbed.test.RecorderManifestRedactionTest",
            "com.slabbed.test.DoubleSlabPlacementNonDestructiveTest",
            "com.slabbed.test.ChainCeilingBridgeTextureTest",
            "com.slabbed.test.ModelStaleSentinelContractTest",
            "com.slabbed.test.ModelStaleSentinelAllocationGateTest",
            "com.slabbed.test.FrozenStoreCollisionAllocationGateTest",
            "com.slabbed.test.FrozenStoreRenderReadAllocationGateTest",
            "com.slabbed.test.RecorderUpgradeContractTest",
            "com.slabbed.test.EnsembleCoherenceContractTest",
            "com.slabbed.test.EnsemblePlacementCoherenceTest",
            "com.slabbed.test.StateChangeAnchorTest",
            "com.slabbed.test.DepartedOccupantFactClearTest",
            "com.slabbed.test.HauntedCarrierCellTest",
            "com.slabbed.test.ConnectingStructuralFreezeTest",
            "com.slabbed.test.AnchoredDepthReadbackTest",
            "com.slabbed.test.CeilingFlushRulingTest",
            "com.slabbed.test.UndersideSeatClampTest",
            "com.slabbed.test.WaterlogReadSymmetryTest",
            "com.slabbed.test.WysiwygMarkerHandOffTest",
            "com.slabbed.test.OffsetRaycastDeepLaneTest",
            "com.slabbed.test.NeighborUpdateInvarianceTest",
            "com.slabbed.test.DeepCompoundTowerLawTest",
            "com.slabbed.test.LandingRuleLawTest",
            "com.slabbed.test.UpwardContinuationValidationTest",
            "com.slabbed.test.DeepObjectOwnerHitRescueTest",
            "com.slabbed.test.HangingUndersideHitRescueTest",
            "com.slabbed.test.PlacementCaptureBoundaryGameTest",
            "com.slabbed.test.RegistrySweepTest",
            "com.slabbed.test.SlabTestKitPaletteTest",
            "com.slabbed.test.anchor.FrozenFlatAttachmentCapacityTest",
            "com.slabbed.test.anchor.PlacementDyAttachmentCapacityTest",
            "com.slabbed.test.PistonPlacementDyTransferTest",
            "com.slabbed.test.FrozenDyModePayloadTest",
            "com.slabbed.test.MinecartRailSeatDepthTest",
            "com.slabbed.test.RailSlopeProfileTest",
            "com.slabbed.test.RailVisualSignalTest",
            "com.slabbed.test.RedstoneWireVisualStepTest",
            "com.slabbed.test.ArmorStandVisibleTopPlacementTest",
            "com.slabbed.test.BoatVisibleSurfacePlacementTest",
            "com.slabbed.test.config.SlabbedConfigFileTest",
            "com.slabbed.test.PotSeatOptionTest",
            "com.slabbed.test.ManualDyAdjustLawTest"
    );

    public static final List<String> INITIALIZERS = List.of(
            "com.slabbed.test.RedstoneGateOnTerrainSlabsPlacementTest$TerrainSlabsRedstoneGateTestEntrypoint",
            "com.slabbed.test.SlabVerticalSupportTerrainSlabsGuardTest$TerrainSlabsVerticalSupportGuardTestEntrypoint",
            "com.slabbed.test.FloorTorchSupportDyTest$TerrainSlabsFloorTorchSupportGuardTestEntrypoint",
            "com.slabbed.test.FenceWallVisibleSupportDyTest$TerrainSlabsFenceWallSupportGuardTestEntrypoint",
            "com.slabbed.test.CantileverBfsTerrainSlabsGuardTest$TerrainSlabsCantileverBfsGuardTestEntrypoint",
            "com.slabbed.test.TerrainSlabsOwnSlabDyGuardTest$TerrainSlabsOwnSlabDyGuardTestEntrypoint",
            "com.slabbed.test.CompatOffsetDeferralPinTest$CompatOffsetDeferralPinTestEntrypoint",
            "com.slabbed.test.SlabLaneConduitTerrainSlabsGuardTest$TerrainSlabsSlabLaneConduitGuardTestEntrypoint",
            "com.slabbed.test.BlockEntityCantileverTerrainSlabsGuardTest$TerrainSlabsBlockEntityCantileverGuardTestEntrypoint",
            "com.slabbed.test.GeometricRemeshSchedulerTest$GeometricRemeshSchedulerTestEntrypoint",
            "com.slabbed.test.PlacementCaptureBoundaryGameTest$TestContentEntrypoint",
            "com.slabbed.test.BottomSlabSpawnProofTest$TerrainSlabsSpawnProofTestEntrypoint",
            "com.slabbed.test.CompatEligibilityPredicateTest$CompatEligibilityFixtureEntrypoint"
    );
}
